import React from "react";

const AboutSectionTwo = () => {
  return (
    <section className="container bg-black py-12">
      <img
        src="/images/about/Frame 55.svg"
        className="m-auto mb-4 w-full md:w-[30%]"
        alt="heading"
      />
      <div className="flex flex-wrap justify-center gap-6">
        <img src="/images/about/Frame 96.svg" alt="center-img" />

        <div className="mt-8 capitalize">
          <p className="decentralized-txt w-full md:mx-auto md:w-[90%]">
            HUMB Assets is a{" "}
            <span className="text-primary">Decentralized Platform </span> that
            makes investing in healthcare simple, secure, and accessible. We
            turn the income generated by real healthcare assets — such as
            medical equipment, hospital space, and diagnostic infrastructure —
            into fractional tokens that offer revenue-sharing benefits to
            investors.Each income stream is verified and linked to a real-world
            asset (NFT), offering full transparency, traceability, and
            confidence.
          </p>
        </div>
      </div>
    </section>
  );
};

export default AboutSectionTwo;
